---
id: 4039494312
is_spam: false
is_deleted: false
post: /2012/08/29/1/
date: 2018-08-14T12:57:53Z
author_fullname: 'Oleg Veres'
author_nickname: 'olegveres'
author_is_anon: false
---

<p>Привет. Выдаёт такие ошибки:<br>Traceback (most recent call last): from dbfpy import dbf - это ругается на "from dbfpy import dbf"<br>File "C:\Users\......\AppData\Local\Programs\Python\Python37-32\lib\site-packages\dbfpy\<a href="http://dbf.py" rel="nofollow noopener" title="dbf.py">dbf.py</a>", line 280<br>    print repr(_rec)</p>
